on:
  push:
    branches:
      - main
env:
  AGENT: "self-hosted"



jobs:
  params:
    runs-on: self-hosted
    outputs:
      runner: ${{steps.agent.outputs.runner}}
    steps:
      - name: set agent
        id: agent
        run: |
          echo "runner=self-hosted" >> $GITHUB_OUTPUT

  test-yaml-reader:
    if: | 
      #${{ needs.params.outputs.runner }} == "ehsan" ||  ${{ needs.params.outputs.runner }} == "self-hosted" 
      ${{ needs.params.outputs.runner }} == "ehsan"

    needs: [params]
    runs-on: ${{ needs.params.outputs.runner }}
#    runs-on: self-hosted
    name: Test read-yaml
    steps:
      - uses: actions/checkout@v1
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './github-runner.yaml'          # File to read from
          key-path: '["spec"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: |
          echo "${{ steps.yaml-data.outputs.data }}"
          
      - name: Display runner
        run: |
          echo "${{ needs.params.outputs.runner }}"


  job:
    needs: ["test-yaml-reader","params"]
    runs-on: ${{ needs.params.outputs.runner }}
    name: Test 
    steps:
      - name: test depe
        run: echo "${{ needs.params.outputs.runner }}"
