on:
  push:
    branches:
      - main
env:
  agent: "self-hosted"
jobs:
  test-yaml-reader:
    runs-on: ${{env.agent}}
    name: Test read-yaml
    steps:
      - uses: actions/checkout@v1
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './github-runner.yaml'          # File to read from
          key-path: '["spec"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
          
